# Generated by Django 4.2.3 on 2023-07-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='country_code',
            field=models.CharField(default='XX', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
