# Generated by Django 4.2.3 on 2023-07-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_country_code_alter_event_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_x',
            field=models.FloatField(default='-83.0057245303377', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='location_y',
            field=models.FloatField(default='39.95698787634127', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='country_code',
            field=models.CharField(default='XXX', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(max_length=255),
        ),
    ]
